# Generated by Django 5.0.3 on 2024-03-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='customerId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
